server:
  port: 8080
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://124.71.113.249:3306/slimsdb
      username: root
      password: '072900'
  main:
    allow-circular-references: true
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

