server:
  port: 80
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3307/slimsdb
      username: root
      password: 123456
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
